version: '3.8'

x-common-variables: &common-variables
  PGUSER: qenjffkg
  PGHOST: ziggy.db.elephantsql.com
  PGPASSWORD: youSqHr4YLjLF-OZeQFbwWi3KFgfIoF1
  PGDATABASE: qenjffkg
  PGPORT: 5432

services:
  nginx:
    depends_on:
      - api
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      <<: *common-variables
      PGUSER: qenjffkg
      PGHOST: ziggy.db.elephantsql.com
      PGPASSWORD: youSqHr4YLjLF-OZeQFbwWi3KFgfIoF1
      PGDATABASE: qenjffkg
      PGPORT: 5432

  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app